### ISSUE TITLE
Will this ever be created?

### ISSUE THREAD

**Issue by calevans** [ParallelDots/ParallelDots-PHP-API#1]
I'd love to play with your API but so far, this is just a skeleton repo. 

Any road map forward?

Cheers! :)
=C=

**Comment by ahwankumar** [comment]
Hi Calevans

Thanks for your interest in our apis. We never had much demand from PHP users so we didn't really have a chance to update this wrapper. We will update this wrapper very soon. Please do check the repo after a few days.

**Comment by ahwankumar** [comment]
The PHP wrapper is updated.
